/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.mml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SVM</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mml.SVM#isGammaSpecified <em>Gamma Specified</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mml.SVM#getGamma <em>Gamma</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mml.SVM#isCSpecified <em>CSpecified</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mml.SVM#getC <em>C</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mml.SVM#isKernelSpecified <em>Kernel Specified</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mml.SVM#getKernel <em>Kernel</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mml.MmlPackage#getSVM()
 * @model
 * @generated
 */
public interface SVM extends MLAlgorithm
{
  /**
   * Returns the value of the '<em><b>Gamma Specified</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gamma Specified</em>' attribute.
   * @see #setGammaSpecified(boolean)
   * @see org.xtext.example.mydsl.mml.MmlPackage#getSVM_GammaSpecified()
   * @model
   * @generated
   */
  boolean isGammaSpecified();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mml.SVM#isGammaSpecified <em>Gamma Specified</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gamma Specified</em>' attribute.
   * @see #isGammaSpecified()
   * @generated
   */
  void setGammaSpecified(boolean value);

  /**
   * Returns the value of the '<em><b>Gamma</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.mml.Gamma}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gamma</em>' attribute.
   * @see org.xtext.example.mydsl.mml.Gamma
   * @see #setGamma(Gamma)
   * @see org.xtext.example.mydsl.mml.MmlPackage#getSVM_Gamma()
   * @model
   * @generated
   */
  Gamma getGamma();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mml.SVM#getGamma <em>Gamma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gamma</em>' attribute.
   * @see org.xtext.example.mydsl.mml.Gamma
   * @see #getGamma()
   * @generated
   */
  void setGamma(Gamma value);

  /**
   * Returns the value of the '<em><b>CSpecified</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CSpecified</em>' attribute.
   * @see #setCSpecified(boolean)
   * @see org.xtext.example.mydsl.mml.MmlPackage#getSVM_CSpecified()
   * @model
   * @generated
   */
  boolean isCSpecified();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mml.SVM#isCSpecified <em>CSpecified</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>CSpecified</em>' attribute.
   * @see #isCSpecified()
   * @generated
   */
  void setCSpecified(boolean value);

  /**
   * Returns the value of the '<em><b>C</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>C</em>' attribute.
   * @see #setC(String)
   * @see org.xtext.example.mydsl.mml.MmlPackage#getSVM_C()
   * @model
   * @generated
   */
  String getC();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mml.SVM#getC <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>C</em>' attribute.
   * @see #getC()
   * @generated
   */
  void setC(String value);

  /**
   * Returns the value of the '<em><b>Kernel Specified</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kernel Specified</em>' attribute.
   * @see #setKernelSpecified(boolean)
   * @see org.xtext.example.mydsl.mml.MmlPackage#getSVM_KernelSpecified()
   * @model
   * @generated
   */
  boolean isKernelSpecified();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mml.SVM#isKernelSpecified <em>Kernel Specified</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kernel Specified</em>' attribute.
   * @see #isKernelSpecified()
   * @generated
   */
  void setKernelSpecified(boolean value);

  /**
   * Returns the value of the '<em><b>Kernel</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.mml.SVMKernel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kernel</em>' attribute.
   * @see org.xtext.example.mydsl.mml.SVMKernel
   * @see #setKernel(SVMKernel)
   * @see org.xtext.example.mydsl.mml.MmlPackage#getSVM_Kernel()
   * @model
   * @generated
   */
  SVMKernel getKernel();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mml.SVM#getKernel <em>Kernel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kernel</em>' attribute.
   * @see org.xtext.example.mydsl.mml.SVMKernel
   * @see #getKernel()
   * @generated
   */
  void setKernel(SVMKernel value);

} // SVM
