/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.mml;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>SVM Kernel</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.mml.MmlPackage#getSVMKernel()
 * @model
 * @generated
 */
public enum SVMKernel implements Enumerator
{
  /**
   * The '<em><b>Rbf</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RBF_VALUE
   * @generated
   * @ordered
   */
  RBF(0, "rbf", "rbf"),

  /**
   * The '<em><b>Linear</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LINEAR_VALUE
   * @generated
   * @ordered
   */
  LINEAR(1, "linear", "linear"),

  /**
   * The '<em><b>Poly</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #POLY_VALUE
   * @generated
   * @ordered
   */
  POLY(2, "poly", "poly"),

  /**
   * The '<em><b>Sigmoid</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SIGMOID_VALUE
   * @generated
   * @ordered
   */
  SIGMOID(3, "sigmoid", "sigmoid");

  /**
   * The '<em><b>Rbf</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RBF
   * @model name="rbf"
   * @generated
   * @ordered
   */
  public static final int RBF_VALUE = 0;

  /**
   * The '<em><b>Linear</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LINEAR
   * @model name="linear"
   * @generated
   * @ordered
   */
  public static final int LINEAR_VALUE = 1;

  /**
   * The '<em><b>Poly</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #POLY
   * @model name="poly"
   * @generated
   * @ordered
   */
  public static final int POLY_VALUE = 2;

  /**
   * The '<em><b>Sigmoid</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SIGMOID
   * @model name="sigmoid"
   * @generated
   * @ordered
   */
  public static final int SIGMOID_VALUE = 3;

  /**
   * An array of all the '<em><b>SVM Kernel</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final SVMKernel[] VALUES_ARRAY =
    new SVMKernel[]
    {
      RBF,
      LINEAR,
      POLY,
      SIGMOID,
    };

  /**
   * A public read-only list of all the '<em><b>SVM Kernel</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<SVMKernel> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>SVM Kernel</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SVMKernel get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SVMKernel result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>SVM Kernel</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SVMKernel getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SVMKernel result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>SVM Kernel</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SVMKernel get(int value)
  {
    switch (value)
    {
      case RBF_VALUE: return RBF;
      case LINEAR_VALUE: return LINEAR;
      case POLY_VALUE: return POLY;
      case SIGMOID_VALUE: return SIGMOID;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private SVMKernel(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //SVMKernel
