/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.mml.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.mml.Gamma;
import org.xtext.example.mydsl.mml.MmlPackage;
import org.xtext.example.mydsl.mml.SVM;
import org.xtext.example.mydsl.mml.SVMKernel;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SVM</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mml.impl.SVMImpl#isGammaSpecified <em>Gamma Specified</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mml.impl.SVMImpl#getGamma <em>Gamma</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mml.impl.SVMImpl#isCSpecified <em>CSpecified</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mml.impl.SVMImpl#getC <em>C</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mml.impl.SVMImpl#isKernelSpecified <em>Kernel Specified</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mml.impl.SVMImpl#getKernel <em>Kernel</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SVMImpl extends MLAlgorithmImpl implements SVM
{
  /**
   * The default value of the '{@link #isGammaSpecified() <em>Gamma Specified</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isGammaSpecified()
   * @generated
   * @ordered
   */
  protected static final boolean GAMMA_SPECIFIED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isGammaSpecified() <em>Gamma Specified</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isGammaSpecified()
   * @generated
   * @ordered
   */
  protected boolean gammaSpecified = GAMMA_SPECIFIED_EDEFAULT;

  /**
   * The default value of the '{@link #getGamma() <em>Gamma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGamma()
   * @generated
   * @ordered
   */
  protected static final Gamma GAMMA_EDEFAULT = Gamma.AUTO;

  /**
   * The cached value of the '{@link #getGamma() <em>Gamma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGamma()
   * @generated
   * @ordered
   */
  protected Gamma gamma = GAMMA_EDEFAULT;

  /**
   * The default value of the '{@link #isCSpecified() <em>CSpecified</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCSpecified()
   * @generated
   * @ordered
   */
  protected static final boolean CSPECIFIED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isCSpecified() <em>CSpecified</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCSpecified()
   * @generated
   * @ordered
   */
  protected boolean cSpecified = CSPECIFIED_EDEFAULT;

  /**
   * The default value of the '{@link #getC() <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getC()
   * @generated
   * @ordered
   */
  protected static final String C_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getC() <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getC()
   * @generated
   * @ordered
   */
  protected String c = C_EDEFAULT;

  /**
   * The default value of the '{@link #isKernelSpecified() <em>Kernel Specified</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isKernelSpecified()
   * @generated
   * @ordered
   */
  protected static final boolean KERNEL_SPECIFIED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isKernelSpecified() <em>Kernel Specified</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isKernelSpecified()
   * @generated
   * @ordered
   */
  protected boolean kernelSpecified = KERNEL_SPECIFIED_EDEFAULT;

  /**
   * The default value of the '{@link #getKernel() <em>Kernel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKernel()
   * @generated
   * @ordered
   */
  protected static final SVMKernel KERNEL_EDEFAULT = SVMKernel.RBF;

  /**
   * The cached value of the '{@link #getKernel() <em>Kernel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKernel()
   * @generated
   * @ordered
   */
  protected SVMKernel kernel = KERNEL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SVMImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MmlPackage.Literals.SVM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isGammaSpecified()
  {
    return gammaSpecified;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGammaSpecified(boolean newGammaSpecified)
  {
    boolean oldGammaSpecified = gammaSpecified;
    gammaSpecified = newGammaSpecified;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MmlPackage.SVM__GAMMA_SPECIFIED, oldGammaSpecified, gammaSpecified));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Gamma getGamma()
  {
    return gamma;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGamma(Gamma newGamma)
  {
    Gamma oldGamma = gamma;
    gamma = newGamma == null ? GAMMA_EDEFAULT : newGamma;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MmlPackage.SVM__GAMMA, oldGamma, gamma));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isCSpecified()
  {
    return cSpecified;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCSpecified(boolean newCSpecified)
  {
    boolean oldCSpecified = cSpecified;
    cSpecified = newCSpecified;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MmlPackage.SVM__CSPECIFIED, oldCSpecified, cSpecified));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getC()
  {
    return c;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setC(String newC)
  {
    String oldC = c;
    c = newC;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MmlPackage.SVM__C, oldC, c));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isKernelSpecified()
  {
    return kernelSpecified;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKernelSpecified(boolean newKernelSpecified)
  {
    boolean oldKernelSpecified = kernelSpecified;
    kernelSpecified = newKernelSpecified;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MmlPackage.SVM__KERNEL_SPECIFIED, oldKernelSpecified, kernelSpecified));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SVMKernel getKernel()
  {
    return kernel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKernel(SVMKernel newKernel)
  {
    SVMKernel oldKernel = kernel;
    kernel = newKernel == null ? KERNEL_EDEFAULT : newKernel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MmlPackage.SVM__KERNEL, oldKernel, kernel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MmlPackage.SVM__GAMMA_SPECIFIED:
        return isGammaSpecified();
      case MmlPackage.SVM__GAMMA:
        return getGamma();
      case MmlPackage.SVM__CSPECIFIED:
        return isCSpecified();
      case MmlPackage.SVM__C:
        return getC();
      case MmlPackage.SVM__KERNEL_SPECIFIED:
        return isKernelSpecified();
      case MmlPackage.SVM__KERNEL:
        return getKernel();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MmlPackage.SVM__GAMMA_SPECIFIED:
        setGammaSpecified((Boolean)newValue);
        return;
      case MmlPackage.SVM__GAMMA:
        setGamma((Gamma)newValue);
        return;
      case MmlPackage.SVM__CSPECIFIED:
        setCSpecified((Boolean)newValue);
        return;
      case MmlPackage.SVM__C:
        setC((String)newValue);
        return;
      case MmlPackage.SVM__KERNEL_SPECIFIED:
        setKernelSpecified((Boolean)newValue);
        return;
      case MmlPackage.SVM__KERNEL:
        setKernel((SVMKernel)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MmlPackage.SVM__GAMMA_SPECIFIED:
        setGammaSpecified(GAMMA_SPECIFIED_EDEFAULT);
        return;
      case MmlPackage.SVM__GAMMA:
        setGamma(GAMMA_EDEFAULT);
        return;
      case MmlPackage.SVM__CSPECIFIED:
        setCSpecified(CSPECIFIED_EDEFAULT);
        return;
      case MmlPackage.SVM__C:
        setC(C_EDEFAULT);
        return;
      case MmlPackage.SVM__KERNEL_SPECIFIED:
        setKernelSpecified(KERNEL_SPECIFIED_EDEFAULT);
        return;
      case MmlPackage.SVM__KERNEL:
        setKernel(KERNEL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MmlPackage.SVM__GAMMA_SPECIFIED:
        return gammaSpecified != GAMMA_SPECIFIED_EDEFAULT;
      case MmlPackage.SVM__GAMMA:
        return gamma != GAMMA_EDEFAULT;
      case MmlPackage.SVM__CSPECIFIED:
        return cSpecified != CSPECIFIED_EDEFAULT;
      case MmlPackage.SVM__C:
        return C_EDEFAULT == null ? c != null : !C_EDEFAULT.equals(c);
      case MmlPackage.SVM__KERNEL_SPECIFIED:
        return kernelSpecified != KERNEL_SPECIFIED_EDEFAULT;
      case MmlPackage.SVM__KERNEL:
        return kernel != KERNEL_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (gammaSpecified: ");
    result.append(gammaSpecified);
    result.append(", gamma: ");
    result.append(gamma);
    result.append(", CSpecified: ");
    result.append(cSpecified);
    result.append(", C: ");
    result.append(c);
    result.append(", kernelSpecified: ");
    result.append(kernelSpecified);
    result.append(", kernel: ");
    result.append(kernel);
    result.append(')');
    return result.toString();
  }

} //SVMImpl
